import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

export default async function ProductsPage() {
  const supabase = await createClient()
  const { data: products, error } = await supabase.from('products').select('*').order('created_at', { ascending: false })
  if (error) throw new Error(error.message)
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold tracking-widest text-teal">PRODUCTS</p><h1 className="mt-2 text-4xl font-black">Your products</h1><p className="mt-2 text-brand/55">Create, edit and publish your product pages.</p></div><Link href="/dashboard/create" className="rounded-xl bg-brand px-5 py-3 text-center font-extrabold text-white">✨ Create with AI</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products?.length ? products.map((p:any)=><Link key={p.id} href={`/dashboard/create?product=${p.id}`} className="overflow-hidden rounded-3xl border border-brand/10 bg-white transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex h-48 items-center justify-center bg-sky">{p.image_url ? <img src={p.image_url} alt="" className="h-full w-full object-cover"/> : <span className="text-5xl">🛍️</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-black">{p.name}</h2><span className="rounded-full bg-beige px-2.5 py-1 text-xs font-bold capitalize">{p.status}</span></div><p className="mt-2 text-xl font-black">{p.currency === 'BDT' ? '৳' : p.currency} {Number(p.price).toLocaleString()}</p><p className="mt-2 line-clamp-2 text-sm text-brand/55">{p.description || 'No description yet.'}</p></div></Link>) : <div className="rounded-3xl border border-dashed border-brand/15 bg-white p-12 text-center sm:col-span-2 xl:col-span-3"><div className="text-5xl">✨</div><h2 className="mt-4 text-2xl font-black">Your product catalog is empty</h2><p className="mx-auto mt-2 max-w-md text-brand/55">Upload a product photo and let SCommerce AI build the first page.</p><Link href="/dashboard/create" className="mt-6 inline-block rounded-xl bg-brand px-5 py-3 font-extrabold text-white">Create first product</Link></div>}</div></div>
}
