import Link from 'next/link';

export default function Home() {
  return <main className="min-h-screen bg-[#f7f8fc]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><div className="text-xl font-extrabold text-brand">SCommerce<span className="text-teal"> AI</span></div><div className="flex gap-3"><Link href="/login" className="rounded-xl px-4 py-2 text-sm font-semibold">Log in</Link><Link href="/dashboard" className="rounded-xl bg-brand px-5 py-2.5 text-sm font-semibold text-white">Open Dashboard</Link></div></nav>
    <section className="mx-auto max-w-7xl px-6 pb-24 pt-20 text-center"><div className="mx-auto max-w-4xl"><span className="rounded-full bg-sky px-4 py-2 text-sm font-semibold text-brand">AI PRODUCT PAGE GENERATOR</span><h1 className="mt-7 text-5xl font-extrabold tracking-tight md:text-7xl">Turn a product photo into a <span className="text-teal">selling page</span> in seconds.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-gray-500">Generate product copy, design a mobile-first landing page, publish it, and collect orders — without coding.</p><div className="mt-9 flex justify-center gap-3"><Link href="/dashboard/create" className="rounded-2xl bg-brand px-7 py-4 font-bold text-white shadow-lg">Create my product page →</Link><Link href="/dashboard" className="rounded-2xl border border-gray-200 bg-white px-7 py-4 font-bold">View dashboard</Link></div></div><div className="mx-auto mt-20 grid max-w-5xl gap-5 md:grid-cols-3"><Feature n="01" title="AI Generate" text="Upload a product and generate persuasive copy automatically."/><Feature n="02" title="Visual Edit" text="Customize sections, colors, prices and calls to action."/><Feature n="03" title="Publish & Sell" text="Share a public page and collect customer orders."/></div></section>
  </main>
}
function Feature({n,title,text}:{n:string;title:string;text:string}) { return <div className="rounded-3xl border border-gray-100 bg-white p-7 text-left shadow-sm"><div className="text-sm font-bold text-teal">{n}</div><h2 className="mt-4 text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-gray-500">{text}</p></div> }
