'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type History = { id:string; product_name:string|null; generation_type:string; language:string|null; created_at:string }
export default function Dashboard(){
 const [products,setProducts]=useState<any[]>([]),[history,setHistory]=useState<History[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[name,setName]=useState('there')
 useEffect(()=>{load()},[])
 async function load(){setLoading(true);const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}setName(user.user_metadata?.full_name?.split(' ')[0]||user.email?.split('@')[0]||'there');const [p,h]=await Promise.all([s.from('products').select('id,name,slug,image_url,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}),s.from('generation_history').select('id,product_name,generation_type,language,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)]);if(p.error||h.error)setError(p.error?.message||h.error?.message||'Could not load dashboard.');setProducts(p.data||[]);setHistory(h.data||[]);setLoading(false)}
 const stats=useMemo(()=>({total:history.length,analysis:history.filter(x=>x.generation_type==='analysis').length,sales:history.filter(x=>x.generation_type==='sales_content').length,creative:history.filter(x=>x.generation_type==='creative').length}),[history])
 return <main className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold tracking-[0.2em] text-teal">AI PRODUCT MARKETING STUDIO</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Good to see you, {name}.</h1><p className="mt-2 max-w-2xl text-brand/55">Turn one product photo into specifications, sales content and branded creatives.</p></div><Link href="/dashboard/create" className="rounded-xl bg-brand px-5 py-3 text-sm font-extrabold text-white">✨ Create with AI</Link></header>
 <section className="mt-7 overflow-hidden rounded-[2rem] bg-brand p-7 text-white md:p-10"><div className="grid items-center gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-sky">ONE PHOTO → COMPLETE SALES KIT</span><h2 className="mt-5 text-3xl font-black leading-tight md:text-5xl">Upload a product photo. Let AI do the selling work.</h2><p className="mt-4 max-w-xl leading-7 text-white/65">Generate persuasive captions, full specifications, hooks, CTAs, ad copy and branded creative content in English or বাংলা.</p><Link href="/dashboard/create" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3 font-extrabold text-brand">✨ Generate Marketing Kit</Link></div><div className="rounded-3xl bg-white/10 p-5"><p className="text-xs font-black uppercase tracking-widest text-sky">Your workspace</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{['📝 Sales captions','📋 Full specifications','🎯 Hooks & CTAs','🖼️ Branded creatives','🎬 Reel scripts','🌐 English + বাংলা'].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm font-bold">{x}</div>)}</div></div></div></section>
 {error&&<div className="mt-4 rounded-xl bg-beige px-4 py-3 text-sm">{error}</div>}
 <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Products',products.length,'📦'],['AI Generations',stats.total,'✨'],['Sales Content',stats.sales,'📝'],['Creatives',stats.creative,'🎨']].map(([label,value,icon])=><Metric key={String(label)} label={String(label)} value={loading?'—':value as any} icon={String(icon)}/>)}</section>
 <section className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-brand/10 bg-white p-6"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">Quick actions</h3><p className="mt-1 text-sm text-brand/50">Jump straight into your next task.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Action href="/dashboard/create" icon="📸" title="Analyze Product" text="Extract specs from one product photo."/><Action href="/dashboard/marketing-kit" icon="📝" title="Sales Content" text="Generate captions, hooks, benefits and CTAs."/><Action href="/dashboard/creative-studio" icon="🎨" title="Creative Studio" text="Create a branded 1080×1080 post."/><Action href="/dashboard/brand-kit" icon="🏷️" title="Brand Kit" text="Keep future outputs on-brand."/></div></div><div className="rounded-3xl border border-brand/10 bg-white p-6"><h3 className="text-xl font-black">Generation mix</h3><div className="mt-6 space-y-5"><Meter label="AI Analysis" value={stats.analysis} total={Math.max(stats.total,1)}/><Meter label="Sales Content" value={stats.sales} total={Math.max(stats.total,1)}/><Meter label="Creatives" value={stats.creative} total={Math.max(stats.total,1)}/></div><Link href="/dashboard/library" className="mt-7 block rounded-xl bg-beige px-4 py-3 text-center text-sm font-black">View library →</Link></div></section>
 <section className="mt-7 rounded-3xl border border-brand/10 bg-white p-6"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">Recent activity</h3><p className="mt-1 text-sm text-brand/50">Your latest AI work.</p></div><Link href="/dashboard/library" className="text-sm font-bold text-teal">View all →</Link></div>{history.length===0?<div className="py-14 text-center text-sm text-brand/50">No activity yet. Start with one product photo.</div>:<div className="mt-5 divide-y divide-brand/10">{history.slice(0,8).map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-beige">{x.generation_type==='analysis'?'🤖':x.generation_type==='sales_content'?'📝':'🎨'}</span><div><div className="font-bold">{x.product_name||'Untitled product'}</div><div className="text-xs text-brand/40">{pretty(x.generation_type)} · {x.language||'—'}</div></div></div><span className="text-xs text-brand/40">{new Date(x.created_at).toLocaleString()}</span></div>)}</div>}</section></main>
}
function Metric({label,value,icon}:{label:string;value:string|number;icon:string}){return <div className="rounded-3xl border border-brand/10 bg-white p-5 shadow-sm"><div className="text-2xl">{icon}</div><p className="mt-4 text-3xl font-black">{value}</p><p className="mt-1 text-sm font-semibold text-brand/45">{label}</p></div>}
function Action({href,icon,title,text}:{href:string;icon:string;title:string;text:string}){return <Link href={href} className="group rounded-2xl border border-brand/10 p-4 transition hover:-translate-y-0.5 hover:border-teal"><div className="text-xl">{icon}</div><div className="mt-3 font-black">{title}</div><p className="mt-1 text-xs leading-5 text-brand/45">{text}</p><div className="mt-3 text-xs font-black text-teal">Open →</div></Link>}
function Meter({label,value,total}:{label:string;value:number;total:number}){const pct=Math.min(100,Math.round(value/total*100));return <div><div className="flex justify-between text-xs font-bold"><span>{label}</span><span className="text-brand/40">{value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-beige"><div className="h-full rounded-full bg-teal" style={{width:`${pct}%`}}/></div></div>}
function pretty(x:string){return x==='analysis'?'AI Analysis':x==='sales_content'?'Sales Content':'Creative'}
